[mypy]
python_version = 3.12
files = main.py, gui_main.py, src
exclude = (?x)(
    ^\.venv/
    | ^config/
    | ^input/
    | ^models/
    | ^output/
  )
warn_unused_configs = True
pretty = True
show_error_codes = True
ignore_missing_imports = True
no_implicit_optional = True
check_untyped_defs = True
warn_return_any = True
warn_redundant_casts = True
warn_unused_ignores = True
namespace_packages = True
explicit_package_bases = True

[mypy-PySide6.*]
ignore_missing_imports = True

[mypy-edge_tts.*]
ignore_missing_imports = True

[mypy-kokoro_onnx.*]
ignore_missing_imports = True

[mypy-soundfile.*]
ignore_missing_imports = True
